### ISSUE TITLE
Bad Visuals when hovering multiple tags

### ISSUE THREAD

**Issue by AinRuizDorado** [yorumicolors/yorumi.nvim#1]
1- Using Lazyvim
2- Version of Neovim 
NVIM v0.10.1
Build type: Release
LuaJIT 2.1.1713484068
3- Problem: When hovering a tag neovim detects where the same tags are used in the same viewport, this creates a color that is not readible, this happens when hovering white tags.

![Bug neovim](https://github.com/user-attachments/assets/f358a5d3-75fa-43c2-bdfc-778b6f93ca14)

Loving the theme, I been using it this last days and I really like it!

**Comment by esskayesss** [comment]
thanks for reporting! im glad you like the theme <3

i pushed a small commit. can you check if it fixes the issue for you?

**Comment by LuisanaMTDev** [comment]
> thanks for reporting! im glad you like the theme <3
> 
> i pushed a small commit. can you check if it fixes the issue for you?

I haved the same problem, it is fixed now!.

**Comment by AinRuizDorado** [comment]
Fixed, Thank you very much!
