### ISSUE TITLE
diffview

### ISSUE THREAD

**Issue by aerosol** [yorumicolors/yorumi.nvim#2]
hey, enjoying the theme!

one issue is, the diff colors look random and it's hard to figure out what's happening. I think this is where a more "standard" palette could be useful.

example:

![image](https://github.com/user-attachments/assets/1b1ac785-6bfd-430a-a221-63159b2e8f19)

**Comment by esskayesss** [comment]
yeah it isn't supposed to look like that... let me push a fix for this really quick.

about the palette... im trying to use the dark versions of yellow, red and greens as highlights and their lighter versions for text... let me push a change and you can tell me what you think of it.

**Comment by esskayesss** [comment]
i pushed a small change. please share your impressions after an update.

**Comment by esskayesss** [comment]
closing as solved. lmk if it needs to be reopened.

**Comment by aerosol** [comment]
much nicer, thank you
